### ISSUE TITLE
Misreporting of platform default dependencies?

### ISSUE THREAD

**Issue by dekellum** [sfackler/cargo-tree#66]
Using cargo-tree 0.26.0, I noticed something strange with a project depending on _flate2_ and its transitive dependencies.  Namely the dependency tree includes _miniz_oxide_c_api_ even though the _rust_backend_ feature is not enabled.   

The flate2 1.0.9 [Cargo.toml](https://github.com/alexcrichton/flate2-rs/blob/1.0.9/Cargo.toml) appears to make the otherwise non-default _miniz_oxide_c_api_ mandatory on wasm32.  But I'm not targeting wasm.  See excerpt below.  Is that what's confusing cargo-tree? 

``` toml
[dependencies]
miniz-sys = { path = "miniz-sys", version = "0.1.11", optional = true }
miniz_oxide_c_api = { version = "0.2", optional = true, features = ["no_c_export"]}

[target.'cfg(all(target_arch = "wasm32", not(target_os = "emscripten")))'.dependencies]
miniz_oxide_c_api = { version = "0.2", features = ["no_c_export"] }

[features]
default = ["miniz-sys"]
zlib = ["libz-sys"]
rust_backend = ["miniz_oxide_c_api"]
```

Here is a minimal reproduction test project:

``` toml
[package]
name = "cargo-tree-opt-dep-test"
version = "0.1.0"
edition = "2018"

[dependencies]
flate2 = "^1.0.9"
brotli = {version = "^3.3.0", optional = true}

[features]
default = []
```

With the following output from `cargo tree`:

``` txt
cargo-tree-opt-dep-test v0.1.0 (/home/david/src/cargo-tree-opt-dep-test)
└── flate2 v1.0.9
    ├── crc32fast v1.2.0
    │   └── cfg-if v0.1.9
    ├── libc v0.2.60
    ├── miniz-sys v0.1.12
    │   └── libc v0.2.60 (*)
    │   [build-dependencies]
    │   └── cc v1.0.38
    └── miniz_oxide_c_api v0.2.3
        ├── crc32fast v1.2.0 (*)
        ├── libc v0.2.60 (*)
        └── miniz_oxide v0.3.0
            └── adler32 v1.0.3
        [build-dependencies]
        └── cc v1.0.38 (*)
```

Note that the optional _brotli_ dependency isn't shown, so `cargo tree` does pay attention to features.  Here is `cargo clean && cargo build` output showing miniz_oxide_c_api isn't built:

``` txt
  Compiling libc v0.2.60
   Compiling cc v1.0.38
   Compiling crc32fast v1.2.0
   Compiling cfg-if v0.1.9
   Compiling miniz-sys v0.1.12
   Compiling flate2 v1.0.9
   Compiling cargo-tree-opt-dep-test v0.1.0 (/home/david/src/cargo-tree-opt-dep-test)
    Finished dev [unoptimized + debuginfo] target(s) in 3.85s
```
